# Adaptation of WezTerm colors to Alacritty (Dark Theme)

[[colors.indexed_colors]]
color = "#ffa066"  # Additional color
index = 16

[[colors.indexed_colors]]
color = "#ff5d62"  # Additional color
index = 17

[colors.bright]
black = "#445055"   # Bright ANSI Black
red = "#e67e80"     # Bright ANSI Red
green = "#a7c080"   # Bright ANSI Green
yellow = "#dbbc7f"  # Bright ANSI Yellow
blue = "#7fbbb3"    # Bright ANSI Blue
magenta = "#d699b6" # Bright ANSI Magenta
cyan = "#83c092"    # Bright ANSI Cyan
white = "#d3c6aa"   # Bright ANSI White

[colors.cursor]
cursor = "#c8c093"  # Cursor color
text = "#c8c093"    # Cursor text color

[colors.normal]
black = "#445055"   # Bright ANSI Black
red = "#e67e80"     # Bright ANSI Red
green = "#a7c080"   # Bright ANSI Green
yellow = "#dbbc7f"  # Bright ANSI Yellow
blue = "#7fbbb3"    # Bright ANSI Blue
magenta = "#d699b6" # Bright ANSI Magenta
cyan = "#83c092"    # Bright ANSI Cyan
white = "#d3c6aa"   # Bright ANSI White

[colors.primary]
background = "#2b3339"  # Background color
foreground = "#d3c6aa"  # Foreground color

[colors.selection]
background = "#2b3339"  # Selection background color
text = "#d3c6aa"        # Selection text color

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 11

[font.normal]
family = "Cascadia Code NF"

[window]
option_as_alt = "Both"
opacity = 0.96

[env]
TERM = "xterm-256color"
