general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 0
}

background {
    monitor =
    color = rgba(11111bff)
}

input-field {
    monitor =
    size = 280, 56
    position = 0, -20
    halign = center
    valign = center

    outline_thickness = 2
    outer_color = rgba(89b4faff)
    inner_color = rgba(1e1e2eff)
    font_color = rgba(cdd6f4ff)
    fade_on_empty = false
    placeholder_text = Password
    dots_center = true
}

label {
    monitor =
    text = $TIME
    color = rgba(cdd6f4ff)
    font_family = Geist
    font_size = 64
    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor =
    text = Type your password to unlock
    color = rgba(a6adc8ff)
    font_family = Geist
    font_size = 16
    position = 0, 55
    halign = center
    valign = center
}
